ui: mocha-bdd
browsers:
  - name: chrome
    version: -1..latest
  - name: firefox
    version: -1..latest
  - name: ie
    version: -1..latest
  - name: iphone
    version: -1..latest
scripts:
  - "requestAnimationFrame-polyfill.js"
